### ISSUE TITLE
Unfriendly error message when a user doesn't have a token

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#218]
```
$ ./bin/pdm sites
Traceback (most recent call last):
  File "./bin/pdm", line 10, in <module>
    pdmcli.main(os.path.join(TOP_PATH, "etc", "system.client.conf"))
  File "/home/centos/pdm/src/pdm/CLI/pdmcli.py", line 84, in main
    args.func(args)
  File "/home/centos/pdm/src/pdm/CLI/user_subcommand.py", line 233, in sitelist
    token = UserCommand._get_token(args.token)
  File "/home/centos/pdm/src/pdm/CLI/user_subcommand.py", line 360, in _get_token
    with open(os.path.expanduser(tokenfile)) as f:
IOError: [Errno 2] No such file or directory: '/home/centos/.pdm/token'
```

**Comment by sfayer** [comment]
It would probably be good to have a better message returned once the login too rather than just printing the raw token string to the console...

**Comment by sfayer** [comment]
And the sites table is missing the end row:
```
---------------------------------------------------------------------------------------------
|site:                                   |description:                                      |
|-------------------------------------------------------------------------------------------|
|Site1                                   |First Test Site                                   |
|Site2                                   |Second Test Site                                  |
|CloudSite1                              |Testing site in cloud (1)                         |
|CloudSite2                              |Testing site in cloud (2)                         |
|UKI-LT2-IC-HEP                          |Imperial College GridPP Site                      |
|NERSC DTN                               |NERSC DTN Service                                 |
```
