### ISSUE TITLE
pdm site login operation does not overwrite a proxy

### ISSUE THREAD

**Issue by martynia** [ic-hep/pdm#232]
When trying to log in to a site for a second time the existing proxy is not overwritten and an error is returned:

<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>Database error while storing proxy</p>

**Comment by sfayer** [comment]
It still doesn't work, something about time comparisons in the database layer. This doesn't seem to get triggered by the test case, so that needs improving too.

```
'2018-05-23 13:41:37,690 pdm.utils.db ERROR Database error while storing proxy
Traceback (most recent call last):
  File "/home/centos/pdm/src/pdm/utils/db.py", line 24, in managed_session
    request.db.session.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 55, in save_obj
    table, states_to_update)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 344, in _collect_update_commands
    attributes.PASSIVE_NO_INITIALIZE)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 674, in get_history
    return History.from_scalar_attribute(self, state, dict_[self.key])
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 1298, in from_scalar_attribute
    elif attribute.is_equal(current, original) is True:
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/type_api.py", line 209, in compare_values
    return x == y
TypeError: can't compare offset-naive and offset-aware datetimes
```
