### ISSUE TITLE
Listing still doesn't work

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#240]
The CLI crashes:
```
Traceback (most recent call last):
  File "bin/pdm", line 10, in <module>
    pdmcli.main(os.path.join(TOP_PATH, "etc", "system.client.conf"))
  File "/home/sf105/code/pdm/src/pdm/CLI/pdmcli.py", line 85, in main
    args.func(args)
  File "/home/sf105/code/pdm/src/pdm/CLI/user_subcommand.py", line 263, in list
    listing_d_value = listing_output['Listing']  # phase 2, capital 'L'
KeyError: 'Listing'
```
The listing_ouptut dictionary looks like:
```
{u'jobid': 32, u'type': u'LIST', u'log': u"Job run on host: [u'pdmdev.grid.hep.ph.ic.ac.uk', [], [u'146.179.248.10']]\nINFO:__main__:gfal listing root: gsiftp://pdmtest1.grid.hep.ph.ic.ac.uk:49999/ at max depth: 0\n", u'elementid': 0, u'listing': {u'gsiftp://pdmtest1.grid.hep.ph.ic.ac.uk:49999/': [{u'st_ctime': 0, u'st_mtime': 1526649749, u'name': u'.', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 224, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33133, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526649749, u'name': u'..', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 224, u'st_gid': 0, u'st_uid': 0, u'st_mode': 33133, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526660177, u'name': u'bin', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 24576, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526650742, u'name': u'boot', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 4096, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526651768, u'name': u'dev', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 2760, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526995777, u'name': u'etc', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 8192, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526995765, u'name': u'home', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 53, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526650169, u'name': u'lib', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 8192, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526774048, u'name': u'lib64', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 24576, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1523422795, u'name': u'media', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 6, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1523422795, u'name': u'mnt', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 6, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1523422795, u'name': u'opt', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 6, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526651758, u'name': u'proc', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 0, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526769028, u'name': u'root', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 226, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16744, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526774049, u'name': u'run', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 780, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526653553, u'name': u'sbin', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 16384, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1523422795, u'name': u'srv', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 6, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526651761, u'name': u'sys', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 0, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16749, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1527651001, u'name': u'tmp', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 172, u'st_gid': 0, u'st_uid': 0, u'st_mode': 18161, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526649750, u'name': u'usr', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 155, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}, {u'st_ctime': 0, u'st_mtime': 1526649750, u'name': u'var', u'st_nlink': 1, u'st_ino': 0, u'st_dev': 0, u'st_size': 267, u'st_gid': 0, u'st_uid': 0, u'st_mode': 16877, u'st_atime': 0}]}}
```

**Comment by sfayer** [comment]
New stack trace:
```
$ bin/pdm list PDMTest1:/
 -r-xr-xr-x   1 0 0   224 2018-05-18 13:22:29  .
 -r-xr-xr-x   1 0 0   224 2018-05-18 13:22:29  ..
 dr-xr-xr-x   1 0 0 24576 2018-05-18 16:16:17  bin
Traceback (most recent call last):
  File "bin/pdm", line 10, in <module>
    pdmcli.main(os.path.join(TOP_PATH, "etc", "system.client.conf"))
  File "pdm/src/pdm/CLI/pdmcli.py", line 85, in main
    args.func(args)
  File "pdm/src/pdm/CLI/user_subcommand.py", line 270, in list
    self._print_formatted_listing(root, listing_d_value)
  File "pdm/src/pdm/CLI/user_subcommand.py", line 328, in _print_formatted_listing
    full_listing, level=level + 1)
  File "pdm/src/pdm/CLI/user_subcommand.py", line 306, in _print_formatted_listing
    listing = full_listing[root]
KeyError: u'gsiftp://pdmtest1.grid.hep.ph.ic.ac.uk:49999/bin'
```
