### ISSUE TITLE
PDM web sign-up page doesn't work

### ISSUE THREAD

**Issue by sfayer** [ic-hep/pdm#326]
After filling out the form and clicking submit, I get a blank page and an exception in the log:
```
'2018-08-02 12:29:13,599 requests.packages.urllib3.connectionpool DEBUG "POST /users/api/v1.0/users HTTP/1.1" 201 189
WSGI application error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/python/threadpool.py", line 190, in _worker
    o = self.q.get()
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib64/python2.7/site-packages/twisted/python/context.py", line 83, in callWithContext
    self.contexts.pop()
  File "/usr/lib64/python2.7/site-packages/twisted/web/wsgi.py", line 340, in run
    self.started = True
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/web/wsgi.py", line 315, in run
    appIterator = self.application(self.environ, self.startResponse)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pdm/pdm/src/pdm/web/WebPageService.py", line 129, in sign_up
    return redirect(url_for("WebPageSevice.front_portal"))
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
werkzeug.routing.BuildError: ('WebPageSevice.front_portal', {}, None)
```

**Comment by sfayer** [comment]
(The account was actually created in the DB correctly).

**Comment by alexanderrichards** [comment]
typo, simple fix
